import './index.css';
import React from 'react';
import { nav } from './Globals';
import HTMLFlipBook from "react-pageflip";

const Page = React.forwardRef((props, ref) => {
    return (
        <div ref={ref}> {/* ref required */}
            {props.children}
        </div>
    );
});

// returns HTMLFlipBook with pages generated by an array of objects with fields: desc, url
function GenBook(pages) {
    return (
        <div id="reader" className="flex justify-center">
            {/* TODO: get image ratio of zines */}
            {/* TODO: data-density="soft" doesn't seem to work */}
            <HTMLFlipBook className="bg-red-300" flippingTime={500} width={600} height={700}>
            {
                pages.map(({desc, url}, index) => {
                    return (
                        <Page alt={desc} key={index} number={index}>
                            <img src={url}></img>
                        </Page>
                    )
                })
            }
            </HTMLFlipBook>
        </div>
    );
}

// can be generated by a db once its working
let pages = [
    {
        desc: "dog portrait cute dog in bed",
        url:  "https://www.shutterstock.com/shutterstock/photos/2019372428/display_1500/stock-photo-dog-portrait-cute-dog-in-bed-2019372428.jpg"
    },
    {
        desc: "golden retriever dog enjoys a bath in a white tub with foam on its head",
        url:  "https://www.shutterstock.com/shutterstock/photos/2403690995/display_1500/stock-photo-golden-retriever-dog-enjoys-a-bath-in-a-white-tub-with-foam-on-its-head-2403690995.jpg"
    },
    {
        desc: "the dog eats food at home",
        url:  "https://www.shutterstock.com/shutterstock/photos/2311206533/display_1500/stock-photo-the-dog-eats-food-at-home-2311206533.jpg"
    },
]

const Reader = () => {
    return (
        <div className="flex flex-col text-sl-title h-screen bg-sl-background">
            {nav}

            <div className="w-7/8 mx-auto">
                {/* TODO: once db works, grab title and pass it to this */}
                <h1 className="pt-5 pb-2 font-serif font-bold text-sl-title text-4xl">Insert Title</h1>
                <hr className="border-sl-text"></hr>

                {/* Reader */}
                <div className="h-full flex flex-col justify-center justify-items-center ">
                    {GenBook(pages)}
                </div>
            </div>
        </div>
    )
}

export default Reader
