import './index.css';
import React from 'react';
import { nav } from './Globals';
import HTMLFlipBook from "react-pageflip";

const Page = React.forwardRef((props, ref) => {
    return (
        <div className="demoPage" ref={ref}>
            <p>{props.children}</p>
            <p>Page number: {props.number}</p>
        </div>
    );
});

// returns HTMLFlipBook with pages generated by an array of objects
function GenBook(pages) {
    return (
        <div id="reader" className="flex justify-center">
            <HTMLFlipBook className="bg-red-300" width={300} height={500}>
            {
                pages.map(({desc, url}, index) => {
                    return (
                        <Page key={index} number={index}>
                            {desc}
                            <img src={url}></img>
                        </Page>
                    )
                })
            }
            </HTMLFlipBook>
        </div>
    );
}

// can be generated by a db once its working
let pages = [
    {
        desc: "dog portrait cute dog in bed",
        url:  "https://www.shutterstock.com/shutterstock/photos/2019372428/display_1500/stock-photo-dog-portrait-cute-dog-in-bed-2019372428.jpg"
    },
    {
        desc: "golden retriever dog enjoys a bath in a white tub with foam on its head",
        url:  "https://www.shutterstock.com/shutterstock/photos/2403690995/display_1500/stock-photo-golden-retriever-dog-enjoys-a-bath-in-a-white-tub-with-foam-on-its-head-2403690995.jpg"
    },
    {
        desc: "the dog eats food at home",
        url:  "https://www.shutterstock.com/shutterstock/photos/2311206533/display_1500/stock-photo-the-dog-eats-food-at-home-2311206533.jpg"
    },
]

const Reader = () => {
    return (
        <div className="flex flex-col text-sl-title h-screen">
            {nav}

            {/* Reader */}
            <div className="h-full flex flex-col justify-center justify-items-center bg-sl-background">
                {GenBook(pages)}
            </div>
        </div>
    )
}

export default Reader
